name: Format Code

on:
  pull_request:
    types: [opened, synchronize]

# Add explicit permissions
permissions:
  contents: write
  pull-requests: write

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install and run Prettier
        run: |
          npm install --global prettier
          prettier --write "**/*.{js,jsx,ts,tsx,json,css,md,html}"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Format code with prettier" 