name: Format Code

on:
  # Manual trigger option
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to format (leave empty for current PR)'
        required: false
        type: string
  # Automatic trigger on PRs
  pull_request:
    types: [opened, synchronize]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.pr_number != '' ? format('refs/pull/{0}/head', github.event.inputs.pr_number) : github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Prettier
        run: npm install --global prettier

      - name: Format Code
        run: prettier --write "**/*.{js,jsx,ts,tsx,json,css,md,html}"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Format code with prettier"
          branch: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.pr_number != '' ? format('pull/{0}/head', github.event.inputs.pr_number) : github.head_ref }} }} 